# Generated by Django 5.1.1 on 2026-03-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
